---
name: conan-package

# Exports the recipe, sources and binaries for Mac, Windows and Linux and upload these to the server such that these can
# be used downstream.
#
# It should run on pushes against main or CURA-* branches, but it will only create the binaries for main and release branches

on:
  workflow_dispatch:
    inputs:
      # FIXME: Not yet implemented
      conan_id:
        required: false
        type: string
        description: 'The full conan package ID, e.g. "curaengine/1.2.3@ultimaker/stable"'
      create_latest_alias:
        required: true
        default: false
        type: boolean
        description: 'Create latest alias'
      create_release:
        required: true
        default: false
        type: boolean
        description: 'Create a conan-package-release'
      create_binaries_windows:
        required: true
        default: false
        type: boolean
        description: 'create binaries Windows'
      create_binaries_linux:
        required: true
        default: false
        type: boolean
        description: 'create binaries Linux'
      create_binaries_macos:
        required: true
        default: false
        type: boolean
        description: 'create binaries Macos'

  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'cmake/**'
      - 'tests/**'
      - 'test_package/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/conan-package.yml'
    branches:
      - main
      - 'CURA-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: curaengine
      release: ${{ github.event.inputs.create_release == 'true' }}

  conan-package-export:
    needs: [ conan-recipe-version ]
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-export.yml@CURA-10831
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
    secrets: inherit

  conan-package-create-macos:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-macos.yml@CURA-10831
    with:
      project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit

  conan-package-create-windows:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-windows.yml@CURA-10831
    with:
      project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit

  conan-package-create-linux:
    needs: [ conan-recipe-version, conan-package-export ]

    uses: ultimaker/cura-workflows/.github/workflows/conan-package-create-linux.yml@CURA-10831
    with:
      project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
    secrets: inherit
